### ISSUE TITLE
Win smart screen

### ISSUE THREAD

**Issue by xdtadas123** [MrShadowDev/doenerium#1]
"Windows protected your PC Microsoft Defender SmartScreen prevented an unrecognized app from starting. Running this app might put your PC at risk." Any way to bypass this security feature ?

**Comment by xdtadas123** [comment]
not fix I mean bypass

**Comment by MrShadowDev** [comment]
Go to settings and disable it!

**Comment by xdtadas123** [comment]
yeah , but I mean when target downloads it and opens, any way to bypass without having program certificated
